CREATE TABLE IF NOT EXISTS MEDICAMENTO (
	id int primary key auto_increment not null,
    nome VARCHAR(150),
    tipo ENUM(
    'Comprimido',
    'Cápsula',
    'Drágea',
    'Pastilha',
    'Goma medicamentosa',
    'Pó',
    'Granulado',
    'Sachê',
    'Xarope',
    'Solução oral',
    'Suspensão oral',
    'Gotas',
    'Spray',
    'Aerossol',
    'Inalável',
    'Creme',
    'Pomada',
    'Gel',
    'Loção',
    'Espuma',
    'Adesivo transdérmico',
    'Supositório',
    'Óvulo vaginal',
    'Colírio',
    'Pomada oftálmica',
    'Gotas otológicas',
    'Spray nasal',
    'Injetável',
    'Implante',
    'Outros' ) NOT NULL,
    categoria ENUM(
    'Analgésico',
    'Antibiótico',
    'Anti-inflamatório',
    'Antialérgico',
    'Antitérmico',
    'Antifúngico',
    'Antiviral',
    'Antidepressivo',
    'Ansiolítico',
    'Antisséptico',
    'Anticoagulante',
    'Anti-hipertensivo',
    'Antidiabético',
    'Anticoncepcional',
    'Antiácido',
    'Antiemético',
    'Laxante',
    'Antidiarreico',
    'Expectorante',
    'Descongestionante',
    'Corticoide',
    'Relaxante muscular',
    'Vitaminas',
    'Outros' ) NOT NULL,
    dosagem VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);