class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.atualizar": "Atualizar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",
            "comum.sistema_titulo": "SysFarm",

            # Tela de Login
            "login.janela_titulo": "Login SysFarm",
            "login.titulo": "━━━━ Login ━━━━",
            "login.cpf": "CPF",
            "login.senha": "Senha",
            "login.entrar": "Autenticar",
            "login.campos_obrigatorios": "Preencha CPF e senha.",
            "login.credenciais_invalidas": "CPF ou senha incorretos.",
            

            # Tela de Usuário
            "usuario.janela_titulo": "Gestão Usuários",
            "usuario.titulo": "Gerenciar Usuários",
            "usuario.dados_frame": "Dados do Usuário",
            "usuario.nome": "Nome",
            "usuario.cpf": "CPF",
            "usuario.senha": "Senha",
            "usuario.cargo": "Cargo",
            "usuario.data_entrada": "Data de Entrada",
            "usuario.confirmar_exclusao": "Deseja realmente excluir este usuário?",
            "usuario.cadastrado_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.excluido_sucesso": "Usuário excluído com sucesso!",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.selecione_da_lista": "Selecione um usuário na lista.",
            "usuario.erro_ao_excluir": "Problemas ao excluir usuário",

            # Tela de Medicamentos
            "medicamento.janela_titulo": "Gestão de Medicamentos",
            "medicamento.titulo": "Gestão de Medicamentos",
            "medicamento.dados_frame": "Dados do Medicamento",
            "medicamento.nome": "Nome",
            "medicamento.tipo": "Tipo",
            "medicamento.categoria": "Categoria",
            "medicamento.dosagem": "Dosagem",
            "medicamento.confirmar_exclusao": "Deseja realmente excluir este medicamento?",
            "medicamento.cadastrado_sucesso": "Medicamento cadastrado com sucesso",
            "medicamento.atualizado_sucesso": "Medicamento atualizado com sucesso!",
            "medicamento.excluido_sucesso": "Medicamento excluído com sucesso!",
            "medicamento.nao_encontrado": "Medicamento não encontrado.",
            "medicamento.selecione_da_lista": "Selecione um medicamento na lista.",
            "medicamento.erro_ao_excluir": "Problemas ao excluir medicamento",

            # Tela de Fornecedores
            "fornecedor.janela_titulo": "Gestão de Fornecedores",
            "fornecedor.titulo": "Gestão de Fornecedores",
            "fornecedor.dados_frame": "Dados do Fornecedor",
            "fornecedor.nome": "Nome",
            "fornecedor.cnpj": "CNPJ",
            "fornecedor.confirmar_exclusao": "Deseja realmente excluir este fornecedor?",
            "fornecedor.cadastrado_sucesso": "Fornecedor cadastrado com sucesso!",
            "fornecedor.atualizado_sucesso": "Fornecedor atualizado com sucesso!",
            "fornecedor.excluido_sucesso": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",
            "fornecedor.selecione_da_lista": "Selecione um fornecedor na lista.",
            "fornecedor.erro_ao_excluir": "Problemas ao excluir fornecedor",

            # Tela de Entrada (Entrada + Lote)
            "entrada.janela_titulo": "Registrar Entrada",
            "entrada.titulo": "Registrar Entrada",
            "entrada.dados_frame": "Dados da Entrada",
            "entrada.medicamento": "Medicamento",
            "entrada.fornecedor": "Fornecedor",
            "entrada.numero_lote": "Número do Lote",
            "entrada.validade": "Validade do Lote",
            "entrada.qtd_entrada": "Quantidade de Entrada",
            "entrada.usuario_responsavel": "Usuário Responsável",
            "entrada.registro_entradas": "Registro de Entradas",
            "entrada.data_entrada": "Data de Entrada",
            "entrada.cadastrado_sucesso": "Entrada registrada com sucesso!",
            "entrada.erro_selecao": "Selecione medicamento, fornecedor e usuário.",
            "entrada.ausencia_campos": "Informe medicamento, fornecedor e usuário.",
            "entrada.status_esgotado": "Esgotado",
            "entrada.status_baixo": "Baixo",
            "entrada.status_disponivel": "Disponível",
            
            "entrada.qtd": "QTD",
            "entrada.validadet": "Validade",
            
            

            # Tela de Saída
            "saida.janela_titulo": "Registrar Saída",
            "saida.titulo": "Registrar Saída",
            "saida.dados_frame": "Dados da Saída",
            "saida.lote_referente": "Lote Referente",
            "saida.medicamento": "Medicamento",
            "saida.qtd_saida": "Quantidade de Saída",
            "saida.tipo_saida": "Tipo de Saída",
            "saida.saidas_anteriores": "Saídas Anteriores",
            "saida.usuario_responsavel": "Usuário Responsável",
            "saida.cadastrado_sucesso": "Saída registrada com sucesso!",
            "saida.erro_selecao": "Selecione o lote e o usuário responsável.",
            "saida.erro_tipo_saida": "Selecione o tipo de saída.",
            "saida.erro_qtd_zero": "Quantidade de saída deve ser maior que zero.",
            "saida.erro_sem_estoque": "Não há estoque registrado para esse lote.",
            "saida.erro_qtd_maior": "Quantidade de saída maior que a disponível no lote.",
            "saida.tipo_venda": "Venda",
            "saida.tipo_avaria": "Avaria",
            "saida.tipo_perda": "Perda",
            "saida.tipo_roubo": "Roubo",
            "saida.data_saida": "Data de Saída",
            
            "saida.lote": "Lote",
            "saida.qtd": "QTD",
            "saida.tipo": "Tipo",
            "saida.responsavel": "Responsável",
            
            

            # Tela de Estoque
            "estoque.janela_titulo": "Visão Geral do Estoque",
            "estoque.titulo": "Visão Geral do Estoque",
            "estoque.medicamento": "Medicamento",
            "estoque.lote": "Lote",
            "estoque.fornecedor": "Fornecedor",
            "estoque.validade": "Validade",
            "estoque.qtd": "Quantidade",
            "estoque.status": "Status",
            "estoque.status_disponivel": "Disponível",
            "estoque.status_baixo": "Baixo",
            "estoque.status_esgotado": "Esgotado",
            "estoque.registrar_entrada": "Registrar Entrada",
            "estoque.registrar_saida": "Registrar Saída",

            # Menu Principal
            "menu.janela_titulo": "SysFarm - Menu Principal",
            "menu.medicamento": "MEDICAMENTO",
            "menu.fornecedor": "FORNECEDOR",
            "menu.estoque": "ESTOQUE",
            "menu.entrada": "ENTRADA",
            "menu.saida": "SAÍDA",
            "menu.usuarios": "USUÁRIOS",
            
            # Medicamento: tipos
            "medicamento.tipo.comprimido": "Comprimido",
            "medicamento.tipo.capsula": "Cápsula",
            "medicamento.tipo.dragea": "Drágea",
            "medicamento.tipo.pastilha": "Pastilha",
            "medicamento.tipo.goma": "Goma medicamentosa",
            "medicamento.tipo.po": "Pó",
            "medicamento.tipo.granulado": "Granulado",
            "medicamento.tipo.sache": "Sachê",
            "medicamento.tipo.xarope": "Xarope",
            "medicamento.tipo.solucao_oral": "Solução oral",
            "medicamento.tipo.suspensao_oral": "Suspensão oral",
            "medicamento.tipo.gotas": "Gotas",
            "medicamento.tipo.spray": "Spray",
            "medicamento.tipo.aerossol": "Aerossol",
            "medicamento.tipo.inalavel": "Inalável",
            "medicamento.tipo.creme": "Creme",
            "medicamento.tipo.pomada": "Pomada",
            "medicamento.tipo.gel": "Gel",
            "medicamento.tipo.locao": "Loção",
            "medicamento.tipo.espuma": "Espuma",
            "medicamento.tipo.adesivo": "Adesivo transdérmico",
            "medicamento.tipo.supositorio": "Supositório",
            "medicamento.tipo.ovulo": "Óvulo vaginal",
            "medicamento.tipo.colirio": "Colírio",
            "medicamento.tipo.pomada_oftalmica": "Pomada oftálmica",
            "medicamento.tipo.gotas_otologicas": "Gotas otológicas",
            "medicamento.tipo.spray_nasal": "Spray nasal",
            "medicamento.tipo.injetavel": "Injetável",
            "medicamento.tipo.implante": "Implante",
            "medicamento.tipo.outros": "Outros",

            # Medicamento: categorias
            "medicamento.categoria.analgesico": "Analgésico",
            "medicamento.categoria.antibiotico": "Antibiótico",
            "medicamento.categoria.antiinflamatorio": "Anti-inflamatório",
            "medicamento.categoria.antialergico": "Antialérgico",
            "medicamento.categoria.antitermico": "Antitérmico",
            "medicamento.categoria.antifungico": "Antifúngico",
            "medicamento.categoria.antiviral": "Antiviral",
            "medicamento.categoria.antidepressivo": "Antidepressivo",
            "medicamento.categoria.ansiolitico": "Ansiolítico",
            "medicamento.categoria.antisseptico": "Antisséptico",
            "medicamento.categoria.anticoagulante": "Anticoagulante",
            "medicamento.categoria.antihipertensivo": "Anti-hipertensivo",
            "medicamento.categoria.antidiabetico": "Antidiabético",
            "medicamento.categoria.anticoncepcional": "Anticoncepcional",
            "medicamento.categoria.antiacido": "Antiácido",
            "medicamento.categoria.antiemetico": "Antiemético",
            "medicamento.categoria.laxante": "Laxante",
            "medicamento.categoria.antidiarreico": "Antidiarreico",
            "medicamento.categoria.expectorante": "Expectorante",
            "medicamento.categoria.descongestionante": "Descongestionante",
            "medicamento.categoria.corticoide": "Corticoide",
            "medicamento.categoria.relaxante_muscular": "Relaxante muscular",
            "medicamento.categoria.vitaminas": "Vitaminas",
            "medicamento.categoria.outros": "Outros",
            
            "medicamento.erro_selecao": "Selecione o tipo e a categoria.",
            
        },
        "eng": {

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.atualizar": "Refresh",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",
            "comum.sistema_titulo": "SysFarm",

            # Login screen
            "login.titulo": "━━━━ Login ━━━━",
            "login.janela_titulo": "SysFarm Login",
            "login.cpf": "CPF",
            "login.senha": "Password",
            "login.entrar": "Sign in",
            "login.campos_obrigatorios": "Enter your CPF and password.",
            "login.credenciais_invalidas": "Incorrect CPF or password.",

            # Users screen
            "usuario.janela_titulo": "User Management",
            "usuario.titulo": "Manage Users",
            "usuario.dados_frame": "User Data",
            "usuario.nome": "Name",
            "usuario.cpf": "CPF",
            "usuario.senha": "Password",
            "usuario.cargo": "        Role",
            "usuario.data_entrada": "Start Date",
            "usuario.confirmar_exclusao": "Do you really want to delete this user?",
            "usuario.cadastrado_sucesso": "User registered successfully!",
            "usuario.atualizado_sucesso": "User updated successfully!",
            "usuario.excluido_sucesso": "User deleted successfully!",
            "usuario.nao_encontrado": "User not found.",
            "usuario.selecione_da_lista": "Select a user from the list.",
            "usuario.erro_ao_excluir": "Problem deleting user",

            # Medications screen
            "medicamento.janela_titulo": "Medication Management",
            "medicamento.titulo": "Medication Management",
            "medicamento.dados_frame": "Medication Data",
            "medicamento.nome": "Name",
            "medicamento.tipo": "Type",
            "medicamento.categoria": "Category",
            "medicamento.dosagem": "Dosage",
            "medicamento.confirmar_exclusao": "Do you really want to delete this medication?",
            "medicamento.cadastrado_sucesso": "Medication registered successfully",
            "medicamento.atualizado_sucesso": "Medication updated successfully!",
            "medicamento.excluido_sucesso": "Medication deleted successfully!",
            "medicamento.nao_encontrado": "Medication not found.",
            "medicamento.selecione_da_lista": "Select a medication from the list.",
            "medicamento.erro_ao_excluir": "Problem deleting medication",

            # Suppliers screen
            "fornecedor.janela_titulo": "Supplier Management",
            "fornecedor.titulo": "Supplier Management",
            "fornecedor.dados_frame": "Supplier Data",
            "fornecedor.nome": "Name",
            "fornecedor.cnpj": "Tax ID",
            "fornecedor.confirmar_exclusao": "Do you really want to delete this supplier?",
            "fornecedor.cadastrado_sucesso": "Supplier registered successfully!",
            "fornecedor.atualizado_sucesso": "Supplier updated successfully!",
            "fornecedor.excluido_sucesso": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.selecione_da_lista": "Select a supplier from the list.",
            "fornecedor.erro_ao_excluir": "Problem deleting supplier",

            # Entry screen (Entry + Batch)
            "entrada.janela_titulo": "Register Entry",
            "entrada.titulo": "Register Entry",
            "entrada.dados_frame": "Entry Data",
            "entrada.medicamento": "Medication",
            "entrada.fornecedor": "Supplier",
            "entrada.numero_lote": "Batch Number",
            "entrada.validade": "Batch Expiration",
            "entrada.qtd_entrada": "Entry Quantity",
            "entrada.registro_entradas": "Entry Log",
            "entrada.data_entrada": "Entry Date",
            "entrada.usuario_responsavel": "Responsible User",
            "entrada.cadastrado_sucesso": "Entry registered successfully!",
            "entrada.erro_selecao": "Select medication, supplier, and user.",
            "entrada.ausencia_campos": "Please provide medication, supplier, and user.",
            "entrada.status_esgotado": "Empty",
            "entrada.status_baixo": "Low",
            "entrada.status_disponivel": "Available",
            
            "entrada.qtd": "QTY",
            "entrada.validadet": "Expiration",
            

            # Exit screen
            "saida.janela_titulo": "Register Exit",
            "saida.titulo": "Register Exit",
            "saida.dados_frame": "Exit Data",
            "saida.lote_referente": "Related Batch",
            "saida.medicamento": "Medication",
            "saida.qtd_saida": "Exit Quantity",
            "saida.tipo_saida": "Exit Type",
            "saida.usuario_responsavel": "Responsible User",
            "saida.saidas_anteriores": "Previous Exits",
            "saida.cadastrado_sucesso": "Exit registered successfully!",
            "saida.erro_selecao": "Select the batch and the responsible user.",
            "saida.erro_tipo_saida": "Select the exit type.",
            "saida.erro_qtd_zero": "Exit quantity must be greater than zero.",
            "saida.erro_sem_estoque": "No stock registered for this batch.",
            "saida.erro_qtd_maior": "Exit quantity is greater than what's available in the batch.",
            "saida.tipo_venda": "Sale",
            "saida.tipo_avaria": "Damage",
            "saida.tipo_perda": "Loss",
            "saida.tipo_roubo": "Theft",
            "saida.data_saida": "Exit Date",
            
            "saida.lote": "Batch",
            "saida.qtd": "QTY",
            "saida.tipo": "Type",
            "saida.responsavel": "Responsible",

            # Stock Overview screen
            "estoque.janela_titulo": "Stock Overview",
            "estoque.titulo": "Stock Overview",
            "estoque.medicamento": "Medication",
            "estoque.lote": "Batch",
            "estoque.fornecedor": "Supplier",
            "estoque.validade": "Expiration",
            "estoque.qtd": "Quantity",
            "estoque.status": "Status",
            "estoque.status_disponivel": "Available",
            "estoque.status_baixo": "Low",
            "estoque.status_esgotado": "Out of Stock",
            "estoque.registrar_entrada": "Register Entry",
            "estoque.registrar_saida": "Register Exit",

            # Main Menu
            "menu.janela_titulo": "SysFarm - Main Menu",
            "menu.bem_vindo": "Welcome",
            "menu.medicamento": "MEDICATION",
            "menu.fornecedor": "SUPPLIER",
            "menu.estoque": "STOCK",
            "menu.entrada": "ENTRY",
            "menu.saida": "EXIT",
            "menu.usuarios": "USERS",
            
            # Medication: types
            "medicamento.tipo.comprimido": "Tablet",
            "medicamento.tipo.capsula": "Capsule",
            "medicamento.tipo.dragea": "Coated tablet",
            "medicamento.tipo.pastilha": "Lozenge",
            "medicamento.tipo.goma": "Medicated gummy",
            "medicamento.tipo.po": "Powder",
            "medicamento.tipo.granulado": "Granules",
            "medicamento.tipo.sache": "Sachet",
            "medicamento.tipo.xarope": "Syrup",
            "medicamento.tipo.solucao_oral": "Oral solution",
            "medicamento.tipo.suspensao_oral": "Oral suspension",
            "medicamento.tipo.gotas": "Drops",
            "medicamento.tipo.spray": "Spray",
            "medicamento.tipo.aerossol": "Aerosol",
            "medicamento.tipo.inalavel": "Inhalable",
            "medicamento.tipo.creme": "Cream",
            "medicamento.tipo.pomada": "Ointment",
            "medicamento.tipo.gel": "Gel",
            "medicamento.tipo.locao": "Lotion",
            "medicamento.tipo.espuma": "Foam",
            "medicamento.tipo.adesivo": "Transdermal patch",
            "medicamento.tipo.supositorio": "Suppository",
            "medicamento.tipo.ovulo": "Vaginal ovule",
            "medicamento.tipo.colirio": "Eye drops",
            "medicamento.tipo.pomada_oftalmica": "Ophthalmic ointment",
            "medicamento.tipo.gotas_otologicas": "Ear drops",
            "medicamento.tipo.spray_nasal": "Nasal spray",
            "medicamento.tipo.injetavel": "Injectable",
            "medicamento.tipo.implante": "Implant",
            "medicamento.tipo.outros": "Other",

            # Medication: categories
            "medicamento.categoria.analgesico": "Analgesic",
            "medicamento.categoria.antibiotico": "Antibiotic",
            "medicamento.categoria.antiinflamatorio": "Anti-inflammatory",
            "medicamento.categoria.antialergico": "Antiallergic",
            "medicamento.categoria.antitermico": "Antipyretic",
            "medicamento.categoria.antifungico": "Antifungal",
            "medicamento.categoria.antiviral": "Antiviral",
            "medicamento.categoria.antidepressivo": "Antidepressant",
            "medicamento.categoria.ansiolitico": "Anxiolytic",
            "medicamento.categoria.antisseptico": "Antiseptic",
            "medicamento.categoria.anticoagulante": "Anticoagulant",
            "medicamento.categoria.antihipertensivo": "Antihypertensive",
            "medicamento.categoria.antidiabetico": "Antidiabetic",
            "medicamento.categoria.anticoncepcional": "Contraceptive",
            "medicamento.categoria.antiacido": "Antacid",
            "medicamento.categoria.antiemetico": "Antiemetic",
            "medicamento.categoria.laxante": "Laxative",
            "medicamento.categoria.antidiarreico": "Antidiarrheal",
            "medicamento.categoria.expectorante": "Expectorant",
            "medicamento.categoria.descongestionante": "Decongestant",
            "medicamento.categoria.corticoide": "Corticosteroid",
            "medicamento.categoria.relaxante_muscular": "Muscle relaxant",
            "medicamento.categoria.vitaminas": "Vitamins",
            "medicamento.categoria.outros": "Other",
            "medicamento.erro_selecao": "Select the type and the category.",
        }
    }
    
    NOMES = {"pt": "Português", "eng": "English"}

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod
    def t(cls, chave):
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)
    

    @classmethod
    def nome_atual(cls):
        return cls.NOMES[cls.ATUAL]

    @classmethod
    def codigo_por_nome(cls, nome):
        return next(c for c, n in cls.NOMES.items() if n == nome)